function jsonGenerator()

CStr = dataread('file', 'lorem.txt', '%s', 'delimiter', '\n');
CStr = CStr(1:2:end);
text = [CStr{:}];
usernames = {'gacruxten',...
'physicscroak',...
'slatydiligent',...
'futurityvacancies',...
'legoashamed',...
'straightmarmora',...
'erectcomplain',...
'deadburp',...
'bootsstarling',...
'whimsicalsonata',...
'powercases',...
'loopholeelbow',...
'smartieflight',...
'pointingtransform',...
'metricphosphorus',...
'musteringgrosbeak',...
'allegedtypewriter',...
'sagittacanker',...
'lidarfilleting',...
'absencebroken',...
'blastpiano',...
'clipclopedible',...
'ordinatescraper',...
'displaypatterns',...
'massivedamaged'};

template = '\n\t"%s": {\n\t\t"sentiment":%d,\n\t\t"tweet_text":"%s",\n\t\t"tweet_user_id":"%s",\n\t\t"tweet_timestamp":"timestamp"\n\t}';
bernieVals = linspace(1,100,1000);
hilaryVals = 0:-1:-1000;
for i = 1:1000
    ndx = randi(length(text)-140);
    kasich = [sprintf(template,'John Kasich',randi([-10 50]),text(ndx:ndx+randi([50,140])),usernames{mod(i,length(usernames))+1}) sprintf(',\n')];
    
    ndx = randi(length(text)-140);
    cruz = [sprintf(template,'Ted Cruz',randi([-10, 10]),text(ndx:ndx+randi([50,140])),usernames{mod(i,length(usernames))+1}) sprintf(',\n')];
    
    ndx = randi(length(text)-140);
    trump = [sprintf(template,'Donald Trump',randi([-10, 10]),text(ndx:ndx+randi([50,140])),usernames{mod(i,length(usernames))+1}) sprintf(',\n')];
    
    ndx = randi(length(text)-140);
    sanders = [sprintf(template,'Bernie Sanders',bernieVals(i),text(ndx:ndx+randi([50,140])),usernames{mod(i,length(usernames))+1}) sprintf(',\n')];
    
    ndx = randi(length(text)-140);
    clinton = [sprintf(template,'Hillary Clinton',hilaryVals(i),text(ndx:ndx+randi([50,140])),usernames{mod(i,length(usernames))+1}) sprintf('\n')];
    
    file = ['{' kasich,cruz,trump,sanders,clinton '}'];
    fh = fopen(['json_' num2str(i) '.json'],'w');
    fprintf(fh,file);
    fclose(fh);
end

end